<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container96EvabL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container96EvabL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container96EvabL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container96EvabL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container96EvabL\App_KernelDevDebugContainer([
    'container.build_hash' => '96EvabL',
    'container.build_id' => '8f4f60bc',
    'container.build_time' => 1685433690,
], __DIR__.\DIRECTORY_SEPARATOR.'Container96EvabL');
